name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main 
    paths:
      - 'docker_files/**' 
      - '.github/workflows/docker-publish.yml'

  workflow_dispatch:  

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get short Git SHA
        run: echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and tag Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/root-tracking-env:latest \
                       -t ghcr.io/${{ github.repository_owner }}/root-tracking-env:${{ env.GIT_SHA }} \
                       -f docker_files/Dockerfile_root_tracking docker_files/.

      - name: Push to GHCR
        run: docker push ghcr.io/${{ github.repository_owner }}/root-tracking-env:latest
